# Generated by Django 5.2.6 on 2025-09-17 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("adopted_section", models.CharField(max_length=256)),
                ("no_of_students", models.IntegerField(default=0)),
                (
                    "coordinate1_lat",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "coordinate1_lng",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "coordinate2_lat",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "coordinate2_lng",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "coordinate3_lat",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "coordinate3_lng",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "coordinate4_lat",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "coordinate4_lng",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField(default="no description provided")),
                ("requirements", models.TextField(default="no requirements")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("cleanup", "cleanup"),
                            ("workshop", "workshop"),
                            ("plantation", "plantation"),
                            ("awareness", "awareness"),
                            ("research", "research"),
                            ("other", "other"),
                        ],
                        default="cleanup",
                        max_length=56,
                    ),
                ),
                ("location", models.CharField(max_length=256)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("is_online", models.BooleanField(default=False)),
                ("expected_participants", models.IntegerField()),
                ("waste_collected", models.IntegerField(default=0)),
                (
                    "organised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.school",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventParticipants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.events",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "event")},
            },
        ),
    ]
