# Generated by Django 5.2.6 on 2025-09-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="events",
            name="is_online",
        ),
    ]
