# Generated by Django 5.2.6 on 2025-09-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_remove_events_is_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="glass_collected",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="events",
            name="miscellaneous_collected",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="events",
            name="paper_collected",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="events",
            name="plastic_collected",
            field=models.IntegerField(default=0),
        ),
    ]
