# Generated by Django 5.2.6 on 2025-09-20 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_events_glass_collected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
