# Generated by Django 5.2.6 on 2025-09-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_events_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="theme_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
    ]
