# Generated by Django 5.2.6 on 2025-09-20 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_school_theme_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventparticipants",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventparticipants",
                to="dashboard.events",
            ),
        ),
    ]
